const EVENTS = [
  "NEW_MESSAGE",
  "RFX_BOUGHT",
  "QUOTATION_APPROVAL",
  "COUNTER_OFFER",
  "PO_RECEIVED",
  "PO_ACCEPTED",
  "DELIVERY_APPROVAL",
  "DELIVERY_CONFIRMED",
  "INVOICE_APPROVAL",
  "PAYMENT_CONFIRMATION",
  "DAILY_RFX"
];

module.exports = EVENTS;